class CartModel {
  String _goodsId;
  String _goodsName;
  int _count;
  String _price;
  String _image;
  bool _selected; //购物车对应商品是否选中

  Autogenerated(
      {String goodsId,
      String goodsName,
      int count,
      String price,
      String image,
      bool selected}) {
    this._goodsId = goodsId;
    this._goodsName = goodsName;
    this._count = count;
    this._price = price;
    this._image = image;
    this._selected = selected;
  }

  String get goodsId => _goodsId;
  set goodsId(String goodsId) => _goodsId = goodsId;
  String get goodsName => _goodsName;
  set goodsName(String goodsName) => _goodsName = goodsName;
  int get count => _count;
  set count(int count) => _count = count;
  String get price => _price;
  set price(String price) => _price = price;
  String get image => _image;
  set image(String image) => _image = image;
  bool get selected => _selected;
  set selected(bool selected) => _selected = selected;

  CartModel.fromJson(Map<String, dynamic> json) {
    _goodsId = json['goodsId'];
    _goodsName = json['goodsName'];
    _count = json['count'];
    _price = json['price'];
    _image = json['image'];
    _selected = json['selected'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['goodsId'] = this._goodsId;
    data['goodsName'] = this._goodsName;
    data['count'] = this._count;
    data['price'] = this._price;
    data['image'] = this._image;
    data['selected'] = this._selected;

    return data;
  }
}
